name: git_hooks
description: Using dart to prevents bad commit or push (git hooks, pre-commit/precommit, pre-push/prepush, post-merge/postmerge and all that stuff...).It is similar to husky.
version: 1.0.1
homepage: https://github.com/xuzhongpeng/git_hooks

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  path: ^1.8.2
  yaml: ^3.1.1
  meta: ^1.8.0
dev_dependencies:
  very_good_analysis: ^3.1.0
  test: ^1.21.6
executables:
  git_hooks:
